# Generated by Django 3.2 on 2021-07-06 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='likes',
            field=models.IntegerField(default=1),
        ),
    ]
