# Generated by Django 3.2 on 2021-07-06 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_posts_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='by',
            field=models.CharField(max_length=30),
        ),
    ]
