# Generated by Django 3.2 on 2021-07-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_rating_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='posts',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='posts',
            name='body',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
