# Generated by Django 3.2 on 2021-07-08 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20210707_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='dislikes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
