# Generated by Django 3.2 on 2021-07-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20210708_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='dislikes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='posts',
            name='likes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
