# Generated by Django 3.2 on 2021-10-04 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20210708_0849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='dislikes',
            new_name='дизлайки',
        ),
    ]
