# Generated by Django 3.2 on 2021-10-04 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_rename_dislikes_posts_дизлайки'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='дизлайки',
            new_name='dislikes',
        ),
    ]
